<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| GNTP version
|--------------------------------------------------------------------------
|
| Define the GNTP version to be used.
|
*/

$config['gntp_version'] = '1.0';


/*
|--------------------------------------------------------------------------
| GNTP global settings
|--------------------------------------------------------------------------
|
| A few essential settings.
|
*/

// The hostname
$config['gntp']['host'] = 'localhost';

// Port which is being used by Growl
$config['gntp']['port'] = 23053;

// How many seconds should the script wait for a response?
$config['gntp']['timeout'] = 15;


/*
|--------------------------------------------------------------------------
| Authorization password
|--------------------------------------------------------------------------
|
| Used to authorize GNTP requests with Growl.
|
| Note: By default, authorization is not required for requests 
| orginating on the local machine.
|
*/

$config['gntp']['password'] = 'test';


/*
|--------------------------------------------------------------------------
| Hashing algorithm
|--------------------------------------------------------------------------
|
| This specifies what algorithm is going to be used for hashing the auth
| key (password).
|
| Currently valid algorithms (GNTP 1.0): md5, sha1, sha256, sha512. Make 
| sure you select one of those.
|
*/

$config['hash_method'] = 'md5';


/*
|--------------------------------------------------------------------------
| Encryption algorithm
|--------------------------------------------------------------------------
|
| Specifies what algorithm should be used for encrypting the request data.
|
| Available options: none (leave it blank), AES, DES, 3DES.
|
| NOTE: It is important to keep in mind that some encryption algorithms 
| require keys that are longer than can be generated by some hashing 
| algorithms. As such, not all hash/encryption combinations are valid 
| (ex: MD5 hash produces a 16 byte result, but AES encryption requires 
| a 24-byte key).
|
*/

$config['encryption_method'] = '';


/*
|--------------------------------------------------------------------------
| REGISTER request headers
|--------------------------------------------------------------------------
|
| All available headers for the REGISTER request. Make sure to set all 
| required headers (those not marked as optional)!
|
*/

// Aplication-Name: <string>
$config['register']['application_name'] = 'FlamingGrowl';

// (Optional) Application-Icon: <url> | <uniqueid>
$config['register']['application_icon'] = '';

// Notifications-Count: <int>
$config['register']['notifications_count'] = 1;

// Notification-Name: <string>
$config['register']['notification_name'] = 'default';

// (Optional) Notification-Display-Name: <string>
$config['register']['notification_display'] = 'Default';

// (Optional) Notification-Enabled: <boolean>
$config['register']['notification_enabled'] = true;

// (Optional) Notification-Icon: <url> | <uniqueid>
$config['register']['notification_icon'] = '';


/*
|--------------------------------------------------------------------------
| NOTIFY request headers
|--------------------------------------------------------------------------
|
| All available headers for the NOTIFY request. Make sure to set all 
| required headers (those not marked as optional)!
|
*/

// Application-Name: <string>
$config['notify']['application_name'] = 'FlamingGrowl';

// Notification-Name: <string>
$config['notify']['name'] = 'default';

// (Optional) Notification-ID: <string>
$config['notify']['id'] = '';

// Notification-Title: <string>
$config['notify']['title'] = 'Title';

// (Optional) Notification-Text: <string>
$config['notify']['text'] = '';

// (Optional) Notification-Sticky: <boolean>
$config['notify']['sticky'] = false;

// (Optional) Notification-Priority: <int>
// Valid values are between -2 and 2, defaults to 0
$config['notify']['priority'] = 0;

// (Optional) Notification-Icon: <url> | <uniqueid>
$config['notify']['icon'] = '';

// (Optional) Notification-Coalescing-ID: <string>
$config['notify']['coalescing_id'] = '';

// (Optional) Notification-Callback-Context: <string>
$config['notify']['callback_context'] = '';

// (Optional) Notification-Callback-Context-Type: <string>
// Required only if 'Notification-Callback-Context' is passed
$config['notify']['callback_context_type'] = '';

// (Optional) Notification-Callback-Target: <string>
$config['notify']['callback_target'] = '';


/*
|--------------------------------------------------------------------------
| SUBSCRIBE request headers
|--------------------------------------------------------------------------
|
| All available headers for the SUBSCRIBE request. Make sure to set all 
| required headers (those not marked as optional)!
|
*/

// Subscriber-ID: <string>
$config['subscribe']['id'] = '';

// Subscriber-Name: <string>
$config['subscribe']['name'] = '';

// (Optional) Subscriber-Port: <int>
$config['subscribe']['port'] = 23053;


/* End of file flaming_growl.php */
/* Location: ./application/config/flaming_growl.php */